/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hoadon;
import java.time.*;
import java.util.*;
/**
 *
 * @author DELL
 */
public class TAOHHD extends javax.swing.JFrame {

//    /**
//     * Creates new form TAOHHD
//     */
    private List<String> ds =  new Vector<>();
    public TAOHHD() {
        initComponents();
    }
    public TAOHHD(String tenNV, String maHD, List<String> list) {
        initComponents();
        this.inTenNV.setText(tenNV);
        this.inMAHD.setText(maHD);
        this.dsCacSach.setListData((Vector<? extends String>) list);
    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TenNV = new javax.swing.JLabel();
        MHD = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dsCacSach = new javax.swing.JList<>();
        btnHuyHD = new javax.swing.JButton();
        btnXuatHD = new javax.swing.JButton();
        inMAHD = new javax.swing.JLabel();
        inTenNV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        TenNV.setText("   Tên Nhân Viên:");

        MHD.setText("      Mã Hóa Đơn:");

        dsCacSach.setBackground(new java.awt.Color(204, 204, 204));
        dsCacSach.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dsCacSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsCacSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dsCacSach);

        btnHuyHD.setText("Hủy Hóa Đơn");
        btnHuyHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHuyHDMouseClicked(evt);
            }
        });

        btnXuatHD.setText("Xuất Hóa Đơn");
        btnXuatHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXuatHDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MHD, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inMAHD, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHuyHD)
                    .addComponent(btnXuatHD))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inMAHD, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXuatHD)
                .addGap(18, 18, 18)
                .addComponent(btnHuyHD)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ///chua xong module nay******************************************************************
    private void dsCacSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsCacSachMouseClicked
        // TODO add your handling code here:        
        this.ds.add(dsCacSach.getSelectedValue());
    }//GEN-LAST:event_dsCacSachMouseClicked

    private void btnXuatHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatHDMouseClicked
        // TODO add your handling code here:
        long tien = updateTongTien(this.ds);
        LocalDateTime thoiGianXuat = LocalDateTime.now();
        this.setVisible(false);
        HoaDon hd = new HoaDon(this.getTenNV(),this.getMAHD(),this.getList(),thoiGianXuat,tien);
        HOADONFORM hdf = new HOADONFORM(hd.getTenNV(),hd.getIDHoaDon(),hd.getListIDSach(),hd.getTGXuat(),tien);
        hdf.setVisible(true);
         
    }//GEN-LAST:event_btnXuatHDMouseClicked

    private void btnHuyHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyHDMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_btnHuyHDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TAOHHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TAOHHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TAOHHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TAOHHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TAOHHD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MHD;
    private javax.swing.JLabel TenNV;
    private javax.swing.JButton btnHuyHD;
    private javax.swing.JButton btnXuatHD;
    private javax.swing.JList<String> dsCacSach;
    private javax.swing.JLabel inMAHD;
    private javax.swing.JLabel inTenNV;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    //setter and getter
    public void setTenNV(String ten){
        this.inTenNV.setText(ten);
    }
    public void setMAHD(String id){
        this.inMAHD.setText(id);
    }
    public void setlist(List<String> list){
        this.dsCacSach.setListData((Vector<? extends String>) list);
    }
    public String getTenNV(){
        return this.inTenNV.getText();
    }
    public String getMAHD(){
        return this.inMAHD.getText();
    }
    public List<String> getList(){
        return ds;
    }
    
    //các hàm xử lý 
    public long updateTongTien(List<String> ds){ 
        long tien = 0;
        for(String item: this.ds){      
            tien += Long.parseLong(item.split("-")[2]);                                                                 
        }
        return tien;
    }
}
